#!/bin/bash

# ProjectFolio CI/CD Pipeline Video Recording Script
# This script helps record a 2-3 minute video demonstrating the entire project

echo "🎬 ProjectFolio Video Recording Guide"
echo "======================================"
echo ""
echo "This script provides a step-by-step guide to record the video."
echo "Please follow the instructions below."
echo ""

# Check for required tools
echo "Checking for required tools..."
if ! command -v asciinema &> /dev/null; then
    echo "⚠️  asciinema not found. Install it with:"
    echo "   npm install -g asciinema"
    echo ""
fi

if ! command -v ffmpeg &> /dev/null; then
    echo "⚠️  ffmpeg not found. Install it for video conversion:"
    echo "   brew install ffmpeg (macOS) or apt install ffmpeg (Linux)"
    echo ""
fi

echo ""
echo "📹 Video Recording Plan (2-3 minutes)"
echo "====================================="
echo ""
echo "Part 1: Project Overview (30 seconds)"
echo "  - Show project structure"
echo "  - Explain key files and directories"
echo "  - Highlight Terraform and GitHub Actions setup"
echo ""
echo "Part 2: CI/CD Pipeline Demonstration (60 seconds)"
echo "  - Show .github/workflows/deploy.yml"
echo "  - Explain the pipeline stages:"
echo "    1. Change detection"
echo "    2. Testing"
echo "    3. Terraform plan/apply"
echo "    4. Application deployment"
echo "    5. Summary generation"
echo ""
echo "Part 3: Terraform Infrastructure (30 seconds)"
echo "  - Show terraform/ directory structure"
echo "  - Explain key resources:"
echo "    - VPC and networking"
echo "    - EC2 and ALB"
echo "    - RDS database"
echo "    - Lambda functions"
echo "    - API Gateway"
echo ""
echo "Part 4: Browser Demo (30-45 seconds)"
echo "  - Start local development server"
echo "  - Navigate through the application:"
echo "    - Homepage"
echo "    - Signup/Login"
echo "    - Dashboard"
echo "    - Project showcase"
echo ""
echo "Part 5: Deployment Demonstration (30 seconds)"
echo "  - Show GitHub Actions in action"
echo "  - Demonstrate change detection"
echo "  - Show Terraform plan output"
echo "  - Show deployment logs"
echo ""

echo "🎥 Recording Instructions"
echo "========================"
echo ""
echo "Option 1: Terminal Recording with asciinema"
echo "  1. Start recording: asciinema rec projectfolio-demo.cast"
echo "  2. Follow the script above"
echo "  3. Stop recording: exit or Ctrl+D"
echo "  4. Convert to video: agg projectfolio-demo.cast projectfolio-demo.gif"
echo ""
echo "Option 2: Screen Recording"
echo "  1. Use OBS Studio, Loom, or built-in screen recorder"
echo "  2. Record terminal and browser windows"
echo "  3. Edit and combine footage"
echo ""
echo "Option 3: GitHub Actions Logs"
echo "  1. Trigger a workflow run"
echo "  2. Screen record the GitHub Actions page"
echo "  3. Show the job summaries and logs"
echo ""

echo "📝 Script for Recording"
echo "======================"
echo ""
echo "Here's a script you can follow while recording:"
echo ""
echo "1. Show project structure:"
echo "   ls -la"
echo "   find . -type f -name '*.tf' | head -20"
echo "   find . -type f -name '*.yml' | head -10"
echo ""
echo "2. Explain CI/CD pipeline:"
echo "   cat .github/workflows/deploy.yml"
echo ""
echo "3. Show Terraform configuration:"
echo "   cd terraform"
echo "   terraform init"
echo "   terraform plan"
echo ""
echo "4. Start local development:"
echo "   cd app"
echo "   npm install"
echo "   npm run dev"
echo ""
echo "5. Demo browser application:"
echo "   Open http://localhost:3000"
echo "   Navigate through the application"
echo ""

echo "✅ Recording Tips"
echo "================"
echo ""
echo "- Keep explanations concise and clear"
echo "- Use a good microphone for audio"
echo "- Ensure screen recording captures full HD (1920x1080)"
echo "- Practice the flow before recording"
echo "- Edit out any mistakes or pauses"
echo ""

echo "🚀 Ready to Record!"
echo "=================="
echo ""
echo "Good luck with your video recording!"
echo "Remember to save the video in a shareable format (MP4, GIF, or WebM)"
